Repository jupyterlab-contrib/jupyterlab-slideshow, pull requests merged in 2025-01, with the labels that each got.

#16 Rename npm package
  README.md
  docs/conf.py
  dodo.py
  examples/overrides.json
  js/_meta/package.json
  js/_meta/src/index.ts
  js/jupyterlab-slideshow/README.md
  js/jupyterlab-slideshow/package.json
  package.json
  pages-lite/overrides.json
  src/jupyterlab_slideshow/_version.py
  yarn.lock
Labels: maintenance

#21 Get back to previous fragment when using shift+space
  js/jupyterlab-slideshow/src/notebook/presenter.ts
Labels: bug

#24 Use toolbar registry for the deck button and move it to the right
  js/jupyterlab-slideshow/schema/plugin.json
  js/jupyterlab-slideshow/src/notebook/extension.ts
  js/jupyterlab-slideshow/src/plugin.ts
Labels: enhancement

#22 Prevent dependabot from using yarn 4
  js/_meta/package.json
  js/jupyterlab-slideshow/package.json
  package.json
Labels: maintenance
